In [2]:
pip install pandas numpy matplotlib seaborn

Requirement already satisfied: pandas in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (2.2.2)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: matplotlib in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: seaborn in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: six>=1.5 in c:\users\chinmoyee bhuyan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Chinmoyee Bhuyan\OneDrive\Desktop\Finance Project\finance.csv")
df.head()

   Unnamed: 0 default student      balance       income
0           1      No      No   729.526495  44361.62507
1           2      No     Yes   817.180407  12106.13470
2           3      No      No  1073.549164  31767.13895
3           4      No      No   529.250605  35704.49394
4           5      No      No   785.655883  38463.49588

In [2]:
df.isnull().sum()

Unnamed: 0    0
default       0
student       0
balance       0
income        0
dtype: int64

In [3]:
df = df.drop("Unnamed: 0", axis=1)

In [4]:
df.head()

  default student      balance       income
0      No      No   729.526495  44361.62507
1      No     Yes   817.180407  12106.13470
2      No      No  1073.549164  31767.13895
3      No      No   529.250605  35704.49394
4      No      No   785.655883  38463.49588

In [5]:
df["default"] = df["default"].map({"Yes": 1, "No": 0})

In [6]:
df["student"] = df["student"].map({"Yes": 1, "No": 0})
df.head()

   default  student      balance       income
0        0        0   729.526495  44361.62507
1        0        1   817.180407  12106.13470
2        0        0  1073.549164  31767.13895
3        0        0   529.250605  35704.49394
4        0        0   785.655883  38463.49588

In [7]:
df["default"].value_counts(normalize=True)

default
0    0.9667
1    0.0333
Name: proportion, dtype: float64

In [8]:
df.groupby("default")["income"].mean()

default
0    33566.166625
1    32089.147124
Name: income, dtype: float64

In [9]:
df.groupby("default")["balance"].mean()

default
0     803.94375
1    1747.82169
Name: balance, dtype: float64

In [10]:
df.groupby("student")["default"].mean()

student
0    0.029195
1    0.043139
Name: default, dtype: float64

In [11]:
df.to_csv("cleaned_finance.csv", index=False)

In [12]:
import sqlite3

In [13]:
conn = sqlite3.connect("finance.db")

In [14]:
df.to_sql("finance", conn, if_exists="replace", index=False)

10000

In [16]:
#default count
pd.read_sql("""
SELECT "default", COUNT(*) 
FROM finance 
GROUP BY "default"
""", conn)

   default  COUNT(*)
0        0      9667
1        1       333

In [17]:
pd.read_sql("""
SELECT "default", AVG(balance) 
FROM finance 
GROUP BY "default"
""", conn)

   default  AVG(balance)
0        0     803.94375
1        1    1747.82169

In [18]:
pd.read_sql("""
SELECT student, AVG("default") 
FROM finance 
GROUP BY student
""", conn)

   student  AVG("default")
0        0        0.029195
1        1        0.043139